strangebuzz/MicroSymfony

.github/workflows/symfony.yml, Makefile, README.md, bin/coverage-checker.php, castor.php, phpunit.xml.dist
=> feat: castor 0.15 upgrade and tests cleanup

README.md, castor.php
* Simplified and better castor title handling
* Added aliases to all commands to match Make targets
=> Feat: better castor title handling + aliases

.php-cs-fixer.dist.php, Makefile, bin/coverage-checker.php, castor.php, src/Helper/StringHelper.php, src/Twig/Extension/EnvExtension.php, src/Twig/Extension/MarkdownExtension.php, tests/Unit/Helper/StringHelperTest.php
* https://github.com/symfony/symfony/blob/7.1/.php-cs-fixer.dist.php
=> feat: synchronize php-cs-fixer rules with Symfony ones

composer.lock, vendor-bin/php-cs-fixer/composer.lock
https://symfony.com/blog/symfony-7-1-1-released
=> chore: Symfony 7.1.1 update

README.md
=> docs: Note for Docker commands on Windows

composer.lock, vendor-bin/php-cs-fixer/composer.lock
https://symfony.com/blog/twig-security-release-possible-sandbox-bypass
=> chore: Twig update for security issue

composer.json, composer.lock, config/bundles.php, symfony.lock
So it's easy to generate code and start making useful things.
=> feat: add the maker bundle

composer.lock, vendor-bin/php-cs-fixer/composer.lock
https://symfony.com/blog/symfony-7-1-5-released
=> chore: Symfony 7.1.5 upgrade

CODE_OF_CONDUCT.md
https://www.contributor-covenant.org/
=> docs: add COC

README.md, scrutinizer-ci.yaml
https://scrutinizer-ci.com/g/strangebuzz/MicroSymfony/?branch=main
=> ci: add scrutinizer-ci

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, LICENSE, README.md, tests/Functional/Controller/StaticRoutesSmokeTest.php
| Issues        | Fix #66
| Doc?      | yes
=> docs: add a contribution quide

Makefile
Spotted by [jms](https://github.com/jmsche) , thanks. :)
| Bug fix?      |no
=> fix: fixed env case in Makefile

README.md
=> docs: added table of content

README.md
=> docs: typos and wording

.env
=> chore: rotate default app secret

README.md
=> docs: added twigstan feature branch

src/Controller/ComposerAction.php, src/Controller/HomeAction.php
As detected in [#95](https://github.com/strangebuzz/MicroSymfony/pull/95) by [ruudk](https://github.com/strangebuzz/MicroSymfony/commits?author=ruudk).
by
=> chore: contoller cleanup

README.md
=> docs: added the Symfony-docker feature branch

README.md
=> docs: added the PHP version badge

bin/console, phpstan.neon
=> Various small cleanup

composer.lock, vendor-bin/php-cs-fixer/composer.lock
* https://symfony.com/blog/symfony-7-1-6-released
=> chore: Symfony 7.1.6 update

scc
=> docs: scc update

README.md
=> docs: added contributing, security, credits and license sections to README

composer.lock, vendor-bin/php-cs-fixer/composer.lock
https://symfony.com/blog/symfony-7-1-7-released
| Cleanup?      | yes (security) 
=> chore: Symfony 7.1.7 update

README.md
=> docs: updated rebase dates

.github/workflows/symfony.yml, README.md, composer.lock, vendor-bin/php-cs-fixer/composer.lock
* https://github.com/shivammathur/setup-php?tab=readme-ov-file#tada-php-support
=> ci: prepare PHP 8.4 usage

README.md
=> docs: added the Twig-CS-Fixer feature branch

composer.json, composer.lock
* Detected with [shipmonk/composer-dependency-analyser](https://github.com/shipmonk-rnd/composer-dependency-analyser)
=> chore: added missing PHP extension in composer file

castor.php
=> chore: fixed fix:all task name

castor.php
=> chore: castor synchronize with Makefile + test v0.21

composer.lock, vendor-bin/php-cs-fixer/composer.lock
* https://symfony.com/blog/symfony-7-1-9-released
| Fixed tickets | na
| New feature?  | yes 
=> chore: Symfony 7.1.9 update

Makefile, castor.php, config/apache/microsymfony.ovh-le-ssl.conf, config/apache/microsymfony.ovh.conf
* https://symfony.com/doc/current/setup/web_server_configuration.html#apache
| Doc added?    | todo
=> feat: add vhosts and letsencrypt Apache2 samples

Makefile, castor.php
=> chore: added missing castor task + disable composer interaction

Makefile
To have the task runner version as Castor.
=> feat: add Make in versions tasks

config/services.yaml, src/Controller/HelloWorldAction.php, templates/App/Controller/HelloWorldAction.html.twig
* Activate bind examples and fixed debug type hint.
| New feature?  | yes 
=> feat: activate and use bind examples in a controller

composer.lock, vendor-bin/php-cs-fixer/composer.lock
* https://symfony.com/blog/symfony-7-2-1-released
=> chore: Symfony 7.2.1 update

src/Twig/Extension/RoutingExtension.php, templates/base.html.twig
* See https://picocss.com/docs/dropdown
=> feat: mark current page in menu

.github/ISSUE_TEMPLATE/1_Bug_report.yaml, .github/ISSUE_TEMPLATE/2_Feature_request.yaml, .php-cs-fixer.dist.php, README.md
=> fix: fixed remaining Symfony 7.1 references

README.md, src/Twig/Extension/MarkdownExtension.php, templates/App/Controller/HomeAction.html.twig, templates/base.html.twig, tests/Integration/Twig/Extension/MarkdownExtensionTest.php
Make work the "buggy" anchors on the website.
| Bug fix?      | yes
=> feat: add the missing anchors on the website homepage + cleanup

assets/styles/app.css, src/Twig/Extension/MarkdownExtension.php, templates/base.html.twig
=> fix: fixed accessibility issues on layout + cleanup

src/Twig/Extension/RoutingExtension.php, templates/base.html.twig
=> chore: better menu

README.md
| Bug fix?      | yes/no
| Deprecations? | yes
=> docs: more built with MicroSymfony websites

config/apache/microsymfony.ovh-le-ssl.conf, tests/Functional/Controller/ComposerActionTest.php, tests/Functional/Controller/FormActionTest.php
=> chore: cleanup

composer.lock, vendor-bin/php-cs-fixer/composer.lock
* https://symfony.com/blog/symfony-7-2-2-released
| Fixed tickets | 
=> chore: Symfony 7.2.2 update

src/Controller/SlugifyAction.php
=> chore: use MapQueryParameter attribute instead of the request service

README.md
* https://contrib.rocks/preview?repo=strangebuzz%2FMicroSymfony
| Deprecations? | yes
=> feat: added contrib.rocks image

README.md
* https://les-tilleuls.coop/en/blog/running-a-symfony-app-on-a-vps-with-docker-and-frankenphp
=> docs: added article reference

config/services.php
=> chore: better config

.github/workflows/symfony.yml, Makefile, castor.php, phpunit.xml.dist
* https://docs.phpunit.de/en/10.5/organizing-tests.html#composing-a-test-suite-using-xml-configuration
=> test: add PHPUnit test suites

composer.json, composer.lock
=> feat: add the FrankenPHP runtime

README.md
=> docs: cleanup for FrankenPHP

composer.lock, vendor-bin/php-cs-fixer/composer.lock
* https://symfony.com/blog/symfony-7-2-3-released
| Deprecations? | none 
=> chore: Symfony 7.2.3 update

SECURITY.md
* https://github.com/COil/squadkick/actions/runs/13040003627/job/36379484259
| Fixed tickets | NO
=> docs: more explanations about the security job

tests/Functional/Controller/StaticRoutesSmokeTest.php, tests/bootstrap.php
* As reported by the feature branch : https://github.com/strangebuzz/MicroSymfony/pull/160
=> chore: cleanup for Psalm level 1

bin/coverage-checker.php
* see https://github.com/strangebuzz/MicroSymfony/pull/160
| Deprecations? | no
=> fix: fixed iterator check (psalm level 1)

README.md
=> docs: added Psalm and Vite-Bundle feature branches references

README.md
* https://www.strangebuzz.com/en/blog/creating-custom-phpstan-rules-for-your-symfony-project
=> docs: add ADR section

README.md
=> docs: notes related to Laragon

README.md, docs/laragon.md
=> docs: notes related to Laragon (tuning)

config/services.php, tests/Integration/ContainerTest.php
* https://gist.github.com/lyrixx/0adb8fd414451596557871d2d9af5695#file-containertest-php
=> feat: add container auto tests

tests/Integration/ContainerTest.php
* As detected in the Psalm feature branch.
=> fix: better if assertion in tests (psalm level1)

README.md, composer.json, composer.lock, config/bundles.php, config/packages/debug.php, symfony.lock
=> feat: add the missing symfony/debug-bundle

composer.lock, vendor-bin/php-cs-fixer/composer.lock
* https://symfony.com/blog/symfony-7-2-4-released
| Fixed tickets | 
| New feature?  | yes/no 
| Doc added?    | yes/no
| Deprecations? | yes/no 
=> chore: Symfony 7.2.4 update

README.md, docs/laragon.md
=> docs: cleanup before release

README.md
=> chore: typos

composer.lock, vendor-bin/php-cs-fixer/composer.lock
* https://symfony.com/blog/symfony-7-2-5-released
=> chore: Symfony 7.2.5 update

composer.lock, phpstan.neon, vendor-bin/php-cs-fixer/composer.lock
https://symfony.com/blog/symfony-7-2-6-released
=> chore: Symfony 7.2.6 update

.github/ISSUE_TEMPLATE/1_Bug_report.yaml, .github/ISSUE_TEMPLATE/2_Feature_request.yaml, .php-cs-fixer.dist.php, README.md, composer.json, composer.lock, config/packages/csrf.php, config/packages/property_info.php, symfony.lock, tests/Functional/Controller/StaticRoutesSmokeTest.php, vendor-bin/php-cs-fixer/composer.lock
* https://symfony.com/blog/symfony-7-3-0-released
* https://symfony.com/blog/symfony-7-3-curated-new-features
| New feature?  | yes 
=> chore: Symfony 7.3 upgrade

src/Controller/FormAction.php, src/Dto/RegisterFormDto.php, src/Form/Type/RegisterForm.php
=> feat: better form example and cleanup
